// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nexus} from '../models';

export function AddOrderSessionLine(arg1:nexus.AddOrderSessionLineInput):Promise<nexus.OrderSessionDetail>;

export function AssignOrderSessionStaff(arg1:nexus.AssignOrderSessionStaffInput):Promise<nexus.OrderSessionDetail>;

export function AuthenticateStaff(arg1:nexus.StaffLoginInput):Promise<nexus.StaffSession>;

export function AuthorizeStaffAction(arg1:nexus.StaffActionApprovalInput):Promise<nexus.ApprovalToken>;

export function CancelPaymentRequest(arg1:string):Promise<nexus.PilotWorkspace>;

export function CloseDay(arg1:nexus.DayCloseInput):Promise<nexus.DayCloseSummary>;

export function CloseInvoice(arg1:nexus.CloseInvoiceInput):Promise<nexus.Dashboard>;

export function CloseOrderSession(arg1:nexus.CloseOrderSessionInput):Promise<nexus.Dashboard>;

export function CreatePaymentRequest(arg1:string):Promise<nexus.PaymentRequest>;

export function CreatePurchaseOrder(arg1:nexus.PurchaseOrderInput):Promise<nexus.PilotWorkspace>;

export function ExportAccountingCSV():Promise<nexus.ExportResult>;

export function ExportBackup(arg1:nexus.BackupInput):Promise<nexus.ExportResult>;

export function ExportDayClosePDF(arg1:string):Promise<nexus.ExportResult>;

export function ExportInvoicePDF(arg1:string):Promise<nexus.ExportResult>;

export function ExportInvoicesCSV(arg1:nexus.InvoiceFilter):Promise<nexus.ExportResult>;

export function GetAccountingSnapshot():Promise<nexus.AccountingSnapshot>;

export function GetAdminAnalytics(arg1:string):Promise<nexus.AdminAnalytics>;

export function GetAuditLog(arg1:number):Promise<Array<nexus.AuditLogEntry>>;

export function GetDashboard():Promise<nexus.Dashboard>;

export function GetInvoiceDetail(arg1:string):Promise<nexus.InvoiceDetail>;

export function GetInvoices(arg1:nexus.InvoiceFilter):Promise<Array<nexus.SaleSummary>>;

export function GetNotifications():Promise<Array<nexus.NotificationRecord>>;

export function GetOrderSessionDetail(arg1:string):Promise<nexus.OrderSessionDetail>;

export function GetPilotWorkspace():Promise<nexus.PilotWorkspace>;

export function GetSyncStatus():Promise<nexus.SyncStatus>;

export function ImportMenuCSV(arg1:nexus.MenuImportInput):Promise<nexus.MenuImportResult>;

export function LinkModifierToItem(arg1:string,arg2:string):Promise<nexus.PilotWorkspace>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function MarkPaymentRequestFailed(arg1:string,arg2:string):Promise<nexus.PilotWorkspace>;

export function MarkPaymentRequestPaid(arg1:string):Promise<nexus.Dashboard>;

export function MarkPrintJobFailed(arg1:string,arg2:string):Promise<nexus.PilotWorkspace>;

export function MarkPrintJobPrinted(arg1:string):Promise<nexus.PilotWorkspace>;

export function OpenOrderSession(arg1:nexus.OpenOrderSessionInput):Promise<nexus.OrderSessionDetail>;

export function QueuePrintJob(arg1:string,arg2:string):Promise<nexus.PrintJob>;

export function RebuildAccountingShell():Promise<nexus.AccountingSnapshot>;

export function ReceiveDelivery(arg1:nexus.DeliveryInput):Promise<nexus.Dashboard>;

export function ReceivePurchaseOrder(arg1:nexus.ReceivePurchaseOrderInput):Promise<nexus.PilotWorkspace>;

export function ReconcileStock(arg1:nexus.ReconcileInput):Promise<nexus.Dashboard>;

export function RecordSale(arg1:nexus.SaleInput):Promise<nexus.Dashboard>;

export function RefundInvoice(arg1:nexus.RefundInvoiceInput):Promise<nexus.Dashboard>;

export function RetryPrintJob(arg1:string):Promise<nexus.PilotWorkspace>;

export function SaveDiningTable(arg1:nexus.DiningTableInput):Promise<nexus.PilotWorkspace>;

export function SaveFloorSection(arg1:nexus.FloorSectionInput):Promise<nexus.PilotWorkspace>;

export function SaveIngredient(arg1:nexus.IngredientInput):Promise<nexus.Dashboard>;

export function SaveIntegrationSetting(arg1:nexus.IntegrationSettingInput):Promise<nexus.PilotWorkspace>;

export function SaveMenuCategory(arg1:nexus.MenuCategoryInput):Promise<nexus.PilotWorkspace>;

export function SaveMenuItem(arg1:nexus.MenuItemInput):Promise<nexus.Dashboard>;

export function SaveMenuModifier(arg1:nexus.MenuModifierInput):Promise<nexus.PilotWorkspace>;

export function SaveOrder(arg1:nexus.SaleInput):Promise<nexus.Dashboard>;

export function SavePrinterConnection(arg1:nexus.PrinterConnectionInput):Promise<nexus.PilotWorkspace>;

export function SaveRestaurantSettings(arg1:nexus.RestaurantSettings):Promise<nexus.PilotWorkspace>;

export function SaveStaff(arg1:nexus.StaffInput):Promise<nexus.PilotWorkspace>;

export function SaveVendor(arg1:nexus.VendorInput):Promise<nexus.PilotWorkspace>;

export function SeedDemoOperations(arg1:number):Promise<nexus.DemoSeedResult>;

export function SendKOT(arg1:string):Promise<nexus.Dashboard>;

export function SendOrderSessionKOT(arg1:string):Promise<nexus.OrderSessionDetail>;

export function SplitInvoice(arg1:nexus.SplitInvoiceInput):Promise<nexus.Dashboard>;

export function TransferOrderSession(arg1:nexus.TableMoveInput):Promise<nexus.OrderSessionDetail>;

export function UpdateIngredientSettings(arg1:nexus.IngredientUpdateInput):Promise<nexus.Dashboard>;

export function UpdateKOTStatus(arg1:string,arg2:string):Promise<nexus.Dashboard>;

export function UpdateRecipe(arg1:nexus.RecipeUpdateInput):Promise<nexus.Dashboard>;

export function ValidateManagerPIN(arg1:string):Promise<nexus.ApprovalToken>;

export function VoidInvoice(arg1:nexus.VoidInvoiceInput):Promise<nexus.Dashboard>;

export function VoidOrderSessionLine(arg1:nexus.SessionLineVoidInput):Promise<nexus.OrderSessionDetail>;
