// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOrderSessionLine(arg1) {
  return window['go']['main']['App']['AddOrderSessionLine'](arg1);
}

export function AuthenticateStaff(arg1) {
  return window['go']['main']['App']['AuthenticateStaff'](arg1);
}

export function AuthorizeStaffAction(arg1) {
  return window['go']['main']['App']['AuthorizeStaffAction'](arg1);
}

export function CancelPaymentRequest(arg1) {
  return window['go']['main']['App']['CancelPaymentRequest'](arg1);
}

export function CloseDay(arg1) {
  return window['go']['main']['App']['CloseDay'](arg1);
}

export function CloseInvoice(arg1) {
  return window['go']['main']['App']['CloseInvoice'](arg1);
}

export function CloseOrderSession(arg1) {
  return window['go']['main']['App']['CloseOrderSession'](arg1);
}

export function CreatePaymentRequest(arg1) {
  return window['go']['main']['App']['CreatePaymentRequest'](arg1);
}

export function CreatePurchaseOrder(arg1) {
  return window['go']['main']['App']['CreatePurchaseOrder'](arg1);
}

export function ExportAccountingCSV() {
  return window['go']['main']['App']['ExportAccountingCSV']();
}

export function ExportBackup(arg1) {
  return window['go']['main']['App']['ExportBackup'](arg1);
}

export function ExportDayClosePDF(arg1) {
  return window['go']['main']['App']['ExportDayClosePDF'](arg1);
}

export function ExportInvoicePDF(arg1) {
  return window['go']['main']['App']['ExportInvoicePDF'](arg1);
}

export function ExportInvoicesCSV(arg1) {
  return window['go']['main']['App']['ExportInvoicesCSV'](arg1);
}

export function GetAccountingSnapshot() {
  return window['go']['main']['App']['GetAccountingSnapshot']();
}

export function GetAdminAnalytics(arg1) {
  return window['go']['main']['App']['GetAdminAnalytics'](arg1);
}

export function GetAuditLog(arg1) {
  return window['go']['main']['App']['GetAuditLog'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetInvoiceDetail(arg1) {
  return window['go']['main']['App']['GetInvoiceDetail'](arg1);
}

export function GetInvoices(arg1) {
  return window['go']['main']['App']['GetInvoices'](arg1);
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetOrderSessionDetail(arg1) {
  return window['go']['main']['App']['GetOrderSessionDetail'](arg1);
}

export function GetPilotWorkspace() {
  return window['go']['main']['App']['GetPilotWorkspace']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function ImportMenuCSV(arg1) {
  return window['go']['main']['App']['ImportMenuCSV'](arg1);
}

export function LinkModifierToItem(arg1, arg2) {
  return window['go']['main']['App']['LinkModifierToItem'](arg1, arg2);
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function MarkPaymentRequestFailed(arg1, arg2) {
  return window['go']['main']['App']['MarkPaymentRequestFailed'](arg1, arg2);
}

export function MarkPaymentRequestPaid(arg1) {
  return window['go']['main']['App']['MarkPaymentRequestPaid'](arg1);
}

export function MarkPrintJobFailed(arg1, arg2) {
  return window['go']['main']['App']['MarkPrintJobFailed'](arg1, arg2);
}

export function MarkPrintJobPrinted(arg1) {
  return window['go']['main']['App']['MarkPrintJobPrinted'](arg1);
}

export function OpenOrderSession(arg1) {
  return window['go']['main']['App']['OpenOrderSession'](arg1);
}

export function QueuePrintJob(arg1, arg2) {
  return window['go']['main']['App']['QueuePrintJob'](arg1, arg2);
}

export function RebuildAccountingShell() {
  return window['go']['main']['App']['RebuildAccountingShell']();
}

export function ReceiveDelivery(arg1) {
  return window['go']['main']['App']['ReceiveDelivery'](arg1);
}

export function ReceivePurchaseOrder(arg1) {
  return window['go']['main']['App']['ReceivePurchaseOrder'](arg1);
}

export function ReconcileStock(arg1) {
  return window['go']['main']['App']['ReconcileStock'](arg1);
}

export function RecordSale(arg1) {
  return window['go']['main']['App']['RecordSale'](arg1);
}

export function RefundInvoice(arg1) {
  return window['go']['main']['App']['RefundInvoice'](arg1);
}

export function RetryPrintJob(arg1) {
  return window['go']['main']['App']['RetryPrintJob'](arg1);
}

export function SaveDiningTable(arg1) {
  return window['go']['main']['App']['SaveDiningTable'](arg1);
}

export function SaveFloorSection(arg1) {
  return window['go']['main']['App']['SaveFloorSection'](arg1);
}

export function SaveIngredient(arg1) {
  return window['go']['main']['App']['SaveIngredient'](arg1);
}

export function SaveIntegrationSetting(arg1) {
  return window['go']['main']['App']['SaveIntegrationSetting'](arg1);
}

export function SaveMenuCategory(arg1) {
  return window['go']['main']['App']['SaveMenuCategory'](arg1);
}

export function SaveMenuItem(arg1) {
  return window['go']['main']['App']['SaveMenuItem'](arg1);
}

export function SaveMenuModifier(arg1) {
  return window['go']['main']['App']['SaveMenuModifier'](arg1);
}

export function SaveOrder(arg1) {
  return window['go']['main']['App']['SaveOrder'](arg1);
}

export function SavePrinterConnection(arg1) {
  return window['go']['main']['App']['SavePrinterConnection'](arg1);
}

export function SaveRestaurantSettings(arg1) {
  return window['go']['main']['App']['SaveRestaurantSettings'](arg1);
}

export function SaveStaff(arg1) {
  return window['go']['main']['App']['SaveStaff'](arg1);
}

export function SaveVendor(arg1) {
  return window['go']['main']['App']['SaveVendor'](arg1);
}

export function SeedDemoOperations(arg1) {
  return window['go']['main']['App']['SeedDemoOperations'](arg1);
}

export function SendKOT(arg1) {
  return window['go']['main']['App']['SendKOT'](arg1);
}

export function SendOrderSessionKOT(arg1) {
  return window['go']['main']['App']['SendOrderSessionKOT'](arg1);
}

export function SplitInvoice(arg1) {
  return window['go']['main']['App']['SplitInvoice'](arg1);
}

export function TransferOrderSession(arg1) {
  return window['go']['main']['App']['TransferOrderSession'](arg1);
}

export function UpdateIngredientSettings(arg1) {
  return window['go']['main']['App']['UpdateIngredientSettings'](arg1);
}

export function UpdateKOTStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateKOTStatus'](arg1, arg2);
}

export function UpdateRecipe(arg1) {
  return window['go']['main']['App']['UpdateRecipe'](arg1);
}

export function ValidateManagerPIN(arg1) {
  return window['go']['main']['App']['ValidateManagerPIN'](arg1);
}

export function VoidInvoice(arg1) {
  return window['go']['main']['App']['VoidInvoice'](arg1);
}

export function VoidOrderSessionLine(arg1) {
  return window['go']['main']['App']['VoidOrderSessionLine'](arg1);
}
